#!/usr/bin/php
<?php

error_reporting(E_ALL);
ini_set('display_errors', 'On');
ini_set('display_startup_errors', 'On');

include('testRabbitMQClient.php');
set_error_handler("logErrors");


$regUsername = strtolower($_GET['registerUsername']);
$regPassword = strtolower($_GET['registerPassword']);

//$today = date("m/d/Y");
//$time = date("h:i:sa");

if($regUsername == '' || $regPassword == '' || $regUsername == null || $regPassword == null){
        echo "Username or Password field left empty, try again.";
        header("location:../index.html?registrationEmpty=blank");

        $logText = " Account registration attempt failed due to null entry.\n";
  	logRegister($logText);      

	exit();
}

$response = registration($regUsername, $regPassword);

if($response == true){
	echo "\nAccount has been created successfully.";
	#  header REFRESH THE LOGIN WITH SUCCESSFUL ACCOUNT CREATION NOTIFICATION.
	
        $logText = " Account registration attempt for User: $regUsername & Password: $regPassword | Registration successful.\n";
	logRegister($logText);

}

elseif($response == false){
	echo "\nAccount already exists.";
        #  header REFRESH THE LOGIN WITH SUCCESSFUL ACCOUNT CREATION NOTIFICATION.

        $logText = " Account registration attempt for User: $regUsername & Password: $regPassword | Failed because username already exists.\n";
	logRegister($logText);


}

?>
